"""Ports — the abstractions high-level code depends on (Dependency Inversion).

The MCP server, the dashboard and the prompt hook all consume a *lesson store*. They
must depend on this ``LessonStore`` Protocol, not on the concrete ``Mem0LessonStore``
(mem0 + Qdrant). ``build_store`` (in ``store``) is the single composition point that
returns a concrete implementation; tests can pass any object satisfying this Protocol.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from .lesson import Lesson


@runtime_checkable
class LessonStore(Protocol):
    """The lesson-memory operations every backend must provide (all async)."""

    async def add(self, lesson: Lesson) -> None: ...
    async def get(self, lesson_id: str) -> Lesson | None: ...
    async def update(self, lesson: Lesson) -> None: ...
    async def delete(self, lesson_id: str) -> bool: ...
    async def search(self, query: str, *, limit: int = 8) -> list[Lesson]: ...
    async def list(self, *, pending_review: bool | None = None) -> list[Lesson]: ...
    async def reinforce(self, lesson_id: str) -> None: ...
    async def record_failure(self, lesson_id: str) -> None: ...
    async def resolve(self, lesson_id: str) -> Lesson | None: ...
